-- The Matrix Data Warehouse Sample Queries
-- Generated by The Matrix Warehouse Builder
--
-- These queries demonstrate how to explore the repository data.
-- Use with: sqlite3 data/matrix.db < data/sample-queries.sql
-- Or with Datasette: datasette data/matrix.db

-- ============================================================================
-- REPOSITORY OVERVIEW
-- ============================================================================

-- Get the latest snapshot summary
SELECT
    timestamp,
    commit_hash,
    branch,
    file_count,
    total_lines,
    agent_count,
    workflow_count
FROM repo_snapshots
ORDER BY id DESC
LIMIT 1;

-- Compare repository growth over time
SELECT
    DATE(timestamp) as date,
    file_count,
    total_lines,
    agent_count,
    workflow_count
FROM repo_snapshots
ORDER BY timestamp;

-- ============================================================================
-- FILE ANALYSIS
-- ============================================================================

-- Top 10 largest files by line count
SELECT
    path,
    file_type,
    line_count,
    size_bytes
FROM files
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
ORDER BY line_count DESC
LIMIT 10;

-- File type distribution
SELECT
    file_type,
    COUNT(*) as file_count,
    SUM(line_count) as total_lines,
    ROUND(AVG(line_count), 2) as avg_lines,
    SUM(size_bytes) as total_bytes
FROM files
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
GROUP BY file_type
ORDER BY file_count DESC;

-- Recently modified files (top 20)
SELECT
    path,
    file_type,
    line_count,
    modified_at
FROM files
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
ORDER BY modified_at DESC
LIMIT 20;

-- Files by directory depth
SELECT
    CASE
        WHEN path NOT LIKE '%/%' THEN 'root'
        WHEN path LIKE '%/%/%/%' THEN 'deep (3+)'
        WHEN path LIKE '%/%/%' THEN 'nested (2)'
        ELSE 'shallow (1)'
    END as depth,
    COUNT(*) as file_count
FROM files
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
GROUP BY depth;

-- ============================================================================
-- DOCUMENTATION ANALYSIS
-- ============================================================================

-- Top 10 longest documents by word count
SELECT
    path,
    title,
    word_count,
    heading_count,
    code_block_count,
    link_count
FROM documents
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
ORDER BY word_count DESC
LIMIT 10;

-- Document statistics summary
SELECT
    COUNT(*) as doc_count,
    SUM(word_count) as total_words,
    ROUND(AVG(word_count), 2) as avg_words,
    SUM(heading_count) as total_headings,
    SUM(code_block_count) as total_code_blocks,
    SUM(link_count) as total_links
FROM documents
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots);

-- Documents with the most code examples
SELECT
    title,
    path,
    code_block_count,
    word_count
FROM documents
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
    AND code_block_count > 0
ORDER BY code_block_count DESC
LIMIT 15;

-- Documents with the most links
SELECT
    title,
    path,
    link_count,
    word_count
FROM documents
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
    AND link_count > 0
ORDER BY link_count DESC
LIMIT 15;

-- ============================================================================
-- AGENT ANALYSIS
-- ============================================================================

-- List all defined agents
SELECT
    name,
    description,
    model,
    tools,
    file_path
FROM agents
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
ORDER BY name;

-- Agents by model
SELECT
    model,
    COUNT(*) as agent_count,
    GROUP_CONCAT(name, ', ') as agents
FROM agents
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
GROUP BY model;

-- Agent tool usage
SELECT
    tools,
    COUNT(*) as agent_count,
    GROUP_CONCAT(name, ', ') as agents
FROM agents
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
GROUP BY tools;

-- ============================================================================
-- WORKFLOW ANALYSIS
-- ============================================================================

-- List all workflows
SELECT
    name,
    triggers,
    jobs,
    file_path
FROM workflows
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
ORDER BY name;

-- Workflow trigger patterns
SELECT
    triggers,
    COUNT(*) as workflow_count,
    GROUP_CONCAT(name, ', ') as workflows
FROM workflows
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
GROUP BY triggers;

-- ============================================================================
-- KNOWLEDGE BASE ANALYSIS
-- ============================================================================

-- Knowledge base categories
SELECT
    category,
    COUNT(*) as entry_count
FROM knowledge_base
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
GROUP BY category
ORDER BY entry_count DESC;

-- All knowledge base entries
SELECT
    category,
    title,
    file_path,
    SUBSTR(content_preview, 1, 100) || '...' as preview
FROM knowledge_base
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
ORDER BY category, title;

-- ============================================================================
-- AGENT CHANGELOG ANALYSIS
-- ============================================================================

-- Chronological agent activity
SELECT
    phase_number,
    phase_name,
    date,
    agent_type,
    task,
    duration,
    success_rate
FROM agent_changelog
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
ORDER BY phase_number;

-- Agent activity by type
SELECT
    agent_type,
    COUNT(*) as activity_count,
    GROUP_CONCAT(DISTINCT phase_name, ' | ') as phases
FROM agent_changelog
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
GROUP BY agent_type;

-- Success rate analysis
SELECT
    agent_type,
    success_rate,
    COUNT(*) as occurrences
FROM agent_changelog
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
    AND success_rate IS NOT NULL
GROUP BY agent_type, success_rate
ORDER BY agent_type, success_rate DESC;

-- ============================================================================
-- CROSS-TABLE ANALYSIS
-- ============================================================================

-- Repository composition (files + docs + agents + workflows)
SELECT
    'Files' as category,
    COUNT(*) as count
FROM files
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
UNION ALL
SELECT
    'Documents' as category,
    COUNT(*) as count
FROM documents
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
UNION ALL
SELECT
    'Agents' as category,
    COUNT(*) as count
FROM agents
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
UNION ALL
SELECT
    'Workflows' as category,
    COUNT(*) as count
FROM workflows
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
UNION ALL
SELECT
    'Knowledge Entries' as category,
    COUNT(*) as count
FROM knowledge_base
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
UNION ALL
SELECT
    'Changelog Entries' as category,
    COUNT(*) as count
FROM agent_changelog
WHERE snapshot_id = (SELECT MAX(id) FROM repo_snapshots);

-- Markdown files with metadata enrichment
SELECT
    f.path,
    f.line_count,
    d.title,
    d.word_count,
    d.heading_count,
    d.code_block_count
FROM files f
LEFT JOIN documents d ON f.path = d.path AND f.snapshot_id = d.snapshot_id
WHERE f.snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
    AND f.file_type = 'md'
ORDER BY f.line_count DESC;

-- ============================================================================
-- HISTORICAL TRENDS (if multiple snapshots exist)
-- ============================================================================

-- Repository growth trajectory
SELECT
    DATE(timestamp) as date,
    file_count,
    file_count - LAG(file_count) OVER (ORDER BY timestamp) as file_growth,
    total_lines,
    total_lines - LAG(total_lines) OVER (ORDER BY timestamp) as line_growth
FROM repo_snapshots
ORDER BY timestamp;

-- File additions and removals between snapshots
WITH file_diffs AS (
    SELECT
        curr.path,
        curr.snapshot_id,
        CASE
            WHEN prev.path IS NULL THEN 'added'
            WHEN curr.hash != prev.hash THEN 'modified'
            ELSE 'unchanged'
        END as status
    FROM files curr
    LEFT JOIN files prev
        ON curr.path = prev.path
        AND prev.snapshot_id = curr.snapshot_id - 1
    WHERE curr.snapshot_id = (SELECT MAX(id) FROM repo_snapshots)
)
SELECT
    status,
    COUNT(*) as count
FROM file_diffs
GROUP BY status;
