#!/usr/bin/env python3

"""
Auto-generates demos_config.json by scanning HTML files for demo metadata

Usage: python3 scripts/generate-demos-config.py

This script scans all HTML files in the project and looks for demo metadata
in <meta> tags, then automatically generates data/config/demos_config.json
"""

import os
import json
import re
from pathlib import Path
from datetime import datetime

# Configuration
PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_FILE = PROJECT_ROOT / 'data' / 'config' / 'demos_config.json'
DEMO_PATHS = [
    'apps/games/pokemon',
    'apps/games',
    'apps',
    '.'  # Root directory for backward compatibility
]

# Metadata keys to look for in HTML files
META_KEYS = {
    'demoId': 'demo:id',
    'demoTitle': 'demo:title',
    'demoDescription': 'demo:description',
    'demoTags': 'demo:tags',
    'demoStatus': 'demo:status',
    'demoStatusLabel': 'demo:statusLabel'
}


def extract_meta_content(html, meta_name):
    """Extract content from meta tag by name"""
    pattern = f'<meta\\s+name=["\']?{re.escape(meta_name)}["\']?\\s+content=["\']([^"\']+)["\']'
    match = re.search(pattern, html, re.IGNORECASE)
    if match:
        return match.group(1)

    # Try reverse order (content before name)
    pattern = f'<meta\\s+content=["\']([^"\']+)["\']\\s+name=["\']?{re.escape(meta_name)}["\']?'
    match = re.search(pattern, html, re.IGNORECASE)
    return match.group(1) if match else None


def extract_demo_metadata(html_path):
    """Extract demo metadata from HTML file"""
    try:
        with open(html_path, 'r', encoding='utf-8') as f:
            html = f.read()

        # Check if this file is marked as a demo
        demo_id = extract_meta_content(html, META_KEYS['demoId'])
        if not demo_id:
            return None

        # Extract metadata
        title = extract_meta_content(html, META_KEYS['demoTitle'])
        description = extract_meta_content(html, META_KEYS['demoDescription'])
        tags_str = extract_meta_content(html, META_KEYS['demoTags'])
        status = extract_meta_content(html, META_KEYS['demoStatus']) or 'ready'
        status_label = extract_meta_content(html, META_KEYS['demoStatusLabel']) or 'LIVE'

        # Validate required fields
        if not demo_id or not title:
            print(f"⚠️  Skipping {html_path}: missing required metadata (id or title)")
            return None

        # Parse tags
        tags = [tag.strip() for tag in tags_str.split(',')] if tags_str else []

        # Get relative path from project root
        rel_path = os.path.relpath(html_path, PROJECT_ROOT).replace('\\', '/')

        metadata = {
            'id': demo_id,
            'title': title,
            'description': description or '',
            'tags': tags,
            'status': status,
            'statusLabel': status_label,
            'path': rel_path
        }

        return metadata

    except Exception as e:
        print(f"❌ Error processing {html_path}: {e}")
        return None


def scan_directory(directory):
    """Recursively scan directory for HTML files"""
    html_files = []

    for root, dirs, files in os.walk(directory):
        # Skip hidden directories, node_modules, archive, etc.
        dirs[:] = [d for d in dirs if not d.startswith('.') and d not in ['node_modules', 'archive', '.steward-backups']]

        for file in files:
            if file.endswith('.html'):
                html_files.append(os.path.join(root, file))

    return html_files


def generate_demos_config():
    """Generate demos config from all HTML files"""
    print("🔍 Scanning for demo files...\n")

    demos = []
    scanned_paths = set()

    # Scan configured paths
    for demo_path in DEMO_PATHS:
        full_path = PROJECT_ROOT / demo_path
        if not full_path.exists():
            continue

        html_files = scan_directory(full_path)

        for html_file in html_files:
            # Skip if already scanned (avoid duplicates)
            if html_file in scanned_paths:
                continue
            scanned_paths.add(html_file)

            metadata = extract_demo_metadata(html_file)
            if metadata:
                demos.append(metadata)
                print(f"✅ Found demo: {metadata['title']} ({metadata['path']})")

    # Sort demos by title
    demos.sort(key=lambda x: x['title'])

    # Create config object
    config = {
        "$schema": "https://json-schema.org/draft-07/schema#",
        "$comment": "Auto-generated by scripts/generate-demos-config.py - DO NOT EDIT MANUALLY",
        "version": "1.0",
        "lastUpdated": datetime.now().isoformat(),
        "description": "Registry of interactive HTML demonstrations showcasing The Matrix capabilities",
        "demos": demos
    }

    # Ensure output directory exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    # Write config file
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print(f"\n✅ Generated {OUTPUT_FILE}")
    print(f"📊 Found {len(demos)} demo(s)\n")

    return demos


if __name__ == '__main__':
    generate_demos_config()
